name: Build EXE and Upload via GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          echo "Running PyInstaller..."
          pyinstaller file_inventory.spec
          echo "PyInstaller build complete. Checking output folder..."

      - name: List files in the dist/ directory
        run: |
          echo "Listing files in dist/ directory"
          Get-ChildItem -Recurse -Path D:\a\file_inventory_builder\file_inventory_builder\dist

      - name: Create GitHub Release (with EXE)
        id: create_release
        run: |
          echo "Attempting to upload EXE to GitHub Releases..."
          $VERSION = (Get-Date -Format "yyyyMMddHHmmss")
          gh release create $VERSION D:\a\file_inventory_builder\file_inventory_builder\dist\file_inventory.exe --title "Release $VERSION" --notes "Auto-generated release for file_inventory.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
