name: Build EXE and Upload via GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          echo "Running PyInstaller..."
          pyinstaller file_inventory.spec
          echo "PyInstaller build complete."

      - name: List dist folder contents
        run: |
          echo "Listing files in dist/ directory:"
          Get-ChildItem -Recurse -Path dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/file_inventory.exe
          asset_name: file_inventory.exe
          asset_content_type: application/octet-stream
