name: Build EXE and Upload via GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller and dependencies
        run: |
          pip install pyinstaller pandas numpy openpyxl xlsxwriter et_xmlfile

      - name: Build EXE with PyInstaller
        run: pyinstaller file_inventory.spec

      - name: List contents of dist
        run: |
          echo "Dist folder contents:"
          Get-ChildItem -Recurse -Path dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: dist/file_inventory.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
